Refactor emit
hyperledger/solang pull request #1015
Opened 2022-09-15 18:40 UTC by LucasSte

Signed-off-by: Lucas Steuernagel <lucas.tnagel@gmail.com>

2022-09-15 20:49 UTC, LucasSte commented
@seanyoung and @xermicus please, have a careful look. I might have messed up with something.

2022-09-16 10:20 UTC, seanyoung requested changes
Layout is much better. I've quickly read through it and can't see any problems

2022-09-16 10:20 UTC, seanyoung commented on src/emit/storage.rs
> +    /// Recursively load a type from bin storage for slot based bin storage
`bin storage` -> `storage`  (everywhere)
I don't know what `bin storage` is

2022-09-16 10:22 UTC, xermicus approved these changes

2022-09-16 15:49 UTC, seanyoung approved these changes

2022-09-16 15:50 UTC, merged