WIP: Create switch instruction
hyperledger/solang pull request #1023
Opened 2022-09-22 04:02 UTC by LucasSte

2022-09-22 10:08 UTC, xermicus approved these changes
LGTM, although it could use some more tests (e.g. no cases and no default at all, multiple default cases, duplicate cases, etc...)

2022-09-22 10:16 UTC, LucasSte commented
> LGTM, although it could use some more tests (e.g. no cases and no default at all, multiple default cases, duplicate cases, etc...)

1. `no cases and no default at all,` The parser does not allow that. You can have only no cases and a default block and cases without a default. There is a test missing for the former. I'm going to add that.
2. `multiple default cases` The parser does not accept that.
3. `duplicate cases`. This is missing. Good point

I'll add those tests!

2022-09-22 10:26 UTC, LucasSte commented
> > LGTM, although it could use some more tests (e.g. no cases and no default at all, multiple default cases, duplicate cases, etc...)
> 
> 1. `no cases and no default at all,` The parser does not allow that. You can have only no cases and a default block and cases without a default. There is a test missing for the former. I'm going to add that.
> 2. `multiple default cases` The parser does not accept that.
> 3. `duplicate cases`. This is missing. Good point
> 
> I'll add those tests!

For the #3, that is a semantic error that I was not detecting.

2022-09-22 12:39 UTC, seanyoung approved these changes
LGTM

2022-09-23 06:37 UTC, LucasSte commented
@seanyoung and @xermicus I am requesting your review again as I implemented Cyrill's suggestions.

2022-09-23 08:51 UTC, seanyoung requested changes

2022-09-23 08:51 UTC, seanyoung commented on src/sema/yul/switch.rs
> +            ));
Please use `Diagnostic::error_with_note()` and provide the location of other entry which is duplicate.

2022-09-23 08:51 UTC, seanyoung commented on src/sema/yul/switch.rs
> +            ));
Also use the location of the literal, not the entire case including block

2022-09-23 08:51 UTC, seanyoung commented on src/codegen/yul/statements.rs
> +fn resolve_switch(
You'd expect `resolve_` in sema, not codegen. How about calling this `fn switch()`?

2022-09-23 11:40 UTC, xermicus approved these changes

2022-09-24 09:17 UTC, seanyoung approved these changes

2022-09-25 09:38 UTC, merged