allow constructor names in substrate
hyperledger/solang pull request #1035
Opened 2022-10-07 14:34 UTC by xermicus

Signed-off-by: Cyrill Leutwiler <bigcyrill@hotmail.com>

2022-10-08 09:44 UTC, seanyoung requested changes
Just some minor documentation comments. Looks good!

2022-10-08 09:44 UTC, seanyoung commented on src/sema/contracts.rs
> +    for f in ns.contracts[contract_no].functions.iter() {
Very pedantic, but is `.iter()` really necessary here.

2022-10-08 09:44 UTC, seanyoung commented on docs/language/contracts.rst
>  If a contract is expected to hold receive value on instantiation, the constructor should be declared ``payable``.
Please fix `hold receive` to `receive` (or something like that)

2022-10-08 09:44 UTC, seanyoung commented on docs/language/contracts.rst
> +    In Substrate, constructors have a name. Solang allows to name constructors in the substrate target:
Not so sure about `In Substrate`. The documentation says `On Substrate` already a lot. We should at least be consistent.

2022-10-08 09:44 UTC, seanyoung commented on docs/language/contracts.rst
> +    Unnamed constructors will be called ``new`` in the metadata.
I think we should mention that the constructor name is only used for the metadata and cannot be used for with the `new contract()` syntax.

2022-10-08 13:46 UTC, LucasSte requested changes

2022-10-08 13:46 UTC, LucasSte commented on docs/language/contracts.rst
> +If a constructor has arguments, those arguments must be supplied when the contract is deployed.
```suggestion
If a constructor has arguments, they must be supplied when the contract is deployed.
```
This is less wordy.

2022-10-08 13:46 UTC, LucasSte commented on docs/targets/substrate.rst
> +- Constructors can be named. Constructors with no name will be called "new" in the generated metadata.
```suggestion
- Constructors can be named. Constructors with no name will be called ``new`` in the generated metadata.
```
This is to maintain consistency with your past usage of `new`.

2022-10-10 08:54 UTC, seanyoung approved these changes

2022-10-10 15:21 UTC, LucasSte approved these changes
Just one nitpick.

2022-10-10 15:21 UTC, LucasSte commented on docs/language/contracts.rst
> +    On Substrate, constructors have a name. Solang allows to name constructors in the substrate target:
```suggestion
    On Substrate, constructors have a name. Solang allows naming constructors in the substrate target:
```
See: https://english.stackexchange.com/questions/60271/grammatical-complements-for-allow/60285#60285

2022-10-10 17:39 UTC, merged