Use named enum for more fields of ast::Expression
hyperledger/solang pull request #1121
Opened 2023-01-04 13:08 UTC by seanyoung

Signed-off-by: Sean Young <sean@darcey.local>

2023-01-04 17:17 UTC, LucasSte requested changes

2023-01-04 17:17 UTC, LucasSte commented on src/bin/languageserver/mod.rs
> +            ast::Expression::BitwiseOr { left, right, .. } => {
This branch and the followings can be merged in a single branch.

2023-01-04 17:17 UTC, LucasSte commented on src/bin/languageserver/mod.rs
> +            ast::Expression::PreIncrement { expr, .. } => {
This branch and the following can be merged.

2023-01-04 17:17 UTC, LucasSte commented on src/sema/ast.rs
> +        unchecked: bool,
Unchecked is not a self-explanatory name.

2023-01-04 17:17 UTC, LucasSte commented on src/sema/ast.rs
> +        right: Box<Expression>,
```suggestion
        true_option: Box<Expression>,
        false_option: Box<Expression>,
```
Is this better?

2023-01-05 08:13 UTC, xermicus approved these changes

2023-01-05 15:14 UTC, LucasSte approved these changes

2023-01-05 16:24 UTC, merged