Update solang-parser/README.md
hyperledger/solang pull request #1213
Opened 2023-03-06 13:37 UTC by smoelius

Update README.md to indicate that breaking changes could occur at any time.

Fixes #1212

2023-03-06 14:15 UTC, seanyoung approved these changes

2023-03-06 14:17 UTC, seanyoung requested changes
Hyperledger requires a `Signed-off-by: real-name <email@address>`, see https://wiki.hyperledger.org/display/TSC/DCO+Validation+During+Contribution+Review

Please add this, thank you

2023-03-07 01:15 UTC, smoelius commented
Hopefully I did this correctly.

2023-03-07 08:22 UTC, seanyoung approved these changes

2023-03-08 19:47 UTC, LucasSte approved these changes

2023-03-09 08:16 UTC, merged