improve resolve pragma
hyperledger/solang pull request #1218
Opened 2023-03-10 08:20 UTC by ilyar

2023-03-10 08:49 UTC, seanyoung requested changes
The idea is great, just some minor changes are needed.
- See comment
- Your commit requires a `Signed-off-by: real name <email address>`
Thank you!

2023-03-16 17:44 UTC, LucasSte approved these changes

2023-03-17 09:05 UTC, xermicus approved these changes

2023-03-17 09:23 UTC, seanyoung commented
We need a real name and email address.

```
Signed-off-by: Ilyar <761285+ilyar@users.noreply.github.com>
```
Is not sufficient, I am afraid.

2023-03-29 08:11 UTC, seanyoung commented
> @seanyoung I think what to answer ... a dilemma or a paradox, if you use a real address for signing, then using a noreply email loses all meaning thinking

Without a correct `Signed-off-by` we will have to close this pull request, sorry.

2023-03-30 15:39 UTC, closed without merging