Constructors on Polkadot can be non-payble
hyperledger/solang pull request #1460
Opened 2023-07-25 19:47 UTC by xermicus

In the `seal1` `instantiate` runtime API, there is no need to send the minimum balance on instantiation (the comment in the docs is not correct).

Hence, constructors on Polkadot can be non-payble

2023-07-26 08:08 UTC, seanyoung requested changes
Looks good.

I noticed that the dispatch code no longer has a special case where if all functions are non-payable, then there is a single value transfer check which is both less code and less gas used in the error case. This could be utilized in the constructor case too.

2023-07-26 08:13 UTC, xermicus commented on integration/polkadot/package.json
> +    "test": "tsc; ts-mocha -t 20000 --exit runtime_errors.spec.ts",
Oh I forgot to push my last commit to enable them again, thanks!

2023-07-26 09:09 UTC, xermicus commented
> there is a single value transfer check 

Very good point thanks. You are right. Either all constructors are payable or all are non-payable (this is enforced in sema).

2023-07-26 10:24 UTC, xermicus commented
Hmm so I thought about it.
- I have not yet seen a real world example with multiple constructors. And if there is a single nonpayable constructor, a single transferred value check will be in the code and exectued anyways. So no real gains here.
- It will make the code size a bit smaller if there are multiple contract functions and all of them are nonpayable. However this is unrelated to this PR.

@seanyoung WDYT about opening an issue so I can just implement it in another PR?

2023-07-26 11:48 UTC, seanyoung approved these changes

2023-07-26 11:49 UTC, seanyoung commented
> @seanyoung WDYT about opening an issue so I can just implement it in another PR?

Note that this functionality was in the dispatch code in emit for functions.

2023-07-26 15:04 UTC, LucasSte reviewed
Is there a test case for when a payable constructor receives no value?

2023-07-26 19:22 UTC, xermicus commented
@LucasSte `polkadot_tests::value.rs` contains two tests that explicitly test payable constructor receiving 0 value either because the user explicit set zero value or it was not set respectively.

2023-07-27 13:46 UTC, LucasSte approved these changes

2023-08-07 09:09 UTC, merged