Add Rename functionality
hyperledger/solang pull request #1514
Opened 2023-09-05 05:22 UTC by chioni16

This feature depends on having the right span information for identifiers in the parse tree. Currently, some changes are needed to either add the missing span information in some cases, or improve the already present spans (look for one-off errors). 

The rest of the "goto-*" functions also depend on the availability of proper spans. But in their case, as no modification is made to the source code, lack of accurate spans is less of an issue. But `rename` does modify the source code and hence having incorrect spans can result in unintentionally overwriting pieces of source code, which is highly undesirable. 

The changes made as part of this PR provide the necessary code for `rename` to work. Correcting the parse tree is expected to be done as part of future PRs

2023-09-09 13:05 UTC, seanyoung commented
Depends on #1490 being merged

2023-09-17 08:38 UTC, seanyoung requested changes
When renaming, the character directly after variable names get deleted.

2023-09-19 04:03 UTC, chioni16 commented
> When renaming, the character directly after variable names get deleted.

I have added a fix. 
This had to do with the way half open/exclusive ranges were handled, as you had suspected. 

Thanks!

2023-09-19 07:53 UTC, seanyoung approved these changes

2023-09-19 17:54 UTC, LucasSte approved these changes

2023-09-19 17:54 UTC, LucasSte commented on src/bin/languageserver/mod.rs
> +    /// * Returns `Ok(None)` when the definition of code object is not found is user code.
```suggestion
    /// * Returns `Ok(None)` when the definition of code object is not found in user code.
```

2023-09-21 13:59 UTC, xermicus approved these changes

2023-09-21 21:07 UTC, merged